import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./Context/AuthContext";
import { AdminProvider } from "./Context/AdminContext";
import { CartProvider } from "./Context/ToggleCart";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <CartProvider>
            <AdminProvider>{children}</AdminProvider>
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
